import { StyleSheet, Dimensions } from "react-native";
import { colors } from "./global.style";

const {width} = Dimensions.get('screen')

export const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colors.background
    },
    boxImage:{
        height:300,
        //paddingHorizontal:16,
        backgroundColor:'#fff',
        //alignItems:'center',
        //justifyContent:'center',
        //marginHorizontal:16,
        //marginTop:24,
        //borderRadius:24
    },
    productImage:{
        height:300,
        paddingTop:40,
        objectFit:'contain',
    },
    buttonBack:{
      
    },

    header:{
        backgroundColor:colors.second,
        flexDirection:'row',
        paddingTop:32,
        alignItems:'center',
        justifyContent:'space-between',
        paddingHorizontal:16,
        paddingBottom:12
    },
    title:{
        fontSize:18,
        fontFamily:'Poppins-SemiBold',
        color:"#fff"
    },
    contentInfo:{
        paddingHorizontal:16,
        paddingTop:16

    },
    boxStar:{
        backgroundColor:colors.primary,
        width:80,
        height:40,
        borderRadius:24,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        gap:4
    },
    contentRate:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    rate:{
        color:"#fff",
        fontSize:14,
        fontFamily:'Poppins-SemiBold'
    },
    price:{
        fontFamily:'Mukta-ExtraBold',
        fontSize:20,
        color:colors.primary
    },
    contentPrice:{
        flexDirection:'row',
        marginTop:16,
        gap:12,
        alignItems:'center'
    },
    boxPlusMinus:{
        flexDirection:'row',
        width:100,
        alignItems:'center',
        justifyContent:'space-between',
    },
    productName:{
        fontFamily:'Poppins-SemiBold',
        fontSize:18,
    },
    button:{
        height:35,
        width:35,
        backgroundColor:colors.primary,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:8
    },
   
    unit:{
        fontFamily:'Mukta-Regular',
        color:'grey'
    },
    textButton:{
        color:"#fff",
        fontFamily:'Mukta-Bold',
        fontSize:18
    },
    total:{
        fontFamily:'Mukta-Bold',
        fontSize:16
    },
    boxButtonTab:{
        flexDirection:'row',
        alignItems:'center',
        gap:12,
        marginTop:8
    },
    buttonTab:{
        height:35,
        //borderBottomColor:'#000',
        //backgroundColor:'#fff',
        /*width:120,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:4*/
    },
    textButtonTab:{
        fontFamily:'Poppins-Medium',
        fontSize:14
    },
    description:{
        fontSize:13,
        fontFamily:'Poppins-Regular',
        color:"#404040",
        lineHeight:20

    },
    contentDescription:{
        backgroundColor:"#fff",
        paddingHorizontal:16,
        paddingVertical:16
    },
    buttonBuy:{
        height:55,
        width:width-160,
        backgroundColor:colors.second,
        borderRadius:12,
        alignItems:'center',
        justifyContent:'center'
    },
    buttonAdd:{
        height:55,
        width:120,
        backgroundColor:colors.primary,
        borderRadius:12,
        alignItems:'center',
        justifyContent:'center',
    },
    boxButtonCheckout:{
        paddingVertical:12,
        paddingHorizontal:16,
        flexDirection:'row',
        justifyContent:'space-between',
        gap:12,
        backgroundColor:'#fff'
    },
    textButtonCheckout:{
        color:"#fff",
        fontFamily:'Poppins-Medium',
        fontSize:14
    }
    
})